image: python:3.5.3

pipelines:
  default:
    - step:
        name: Build and test
        caches:
          - pip
          - tox
        script:
          - pip install virtualenv tox
          - tox
    - step:
        name: Deploy to test
        deployment: test
        caches:
          - pip
          - tox
        script:
          - pip install virtualenv tox
          - tox
    - step:
        name: Deploy to staging
        deployment: staging
        trigger: manual
        caches:
          - pip
          - tox
        script:
          - pip install twine wheel tox
          - python setup.py bdist_wheel --universal
    - step:
        name: Deploy to production
        deployment: production
        trigger: manual
        script:
          - pip install twine wheel tox
          - python setup.py bdist_wheel --universal
          - twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD --skip-existing dist/*

definitions:
  caches:
    tox: .tox
