image: python:3.7

pipelines:
  default:
    - step:
        name: Build and test
        max-time: 10
        caches:
          - pip
        script:
          - pip install pipenv
          - pipenv install --deploy --system --dev
          - pylint --rcfile .pylintrc pyvisainstrument
          - NI_VISA_PATH='@py' pytest
    - step:
        name: Deploy to test
        deployment: test
        max-time: 10
        caches:
          - pip
        script:
          - pip install pipenv
          - pipenv install --deploy --system --dev
          - pylint --rcfile .pylintrc pyvisainstrument
          - NI_VISA_PATH='@py' pytest
    - step:
        name: Deploy to staging
        deployment: staging
        max-time: 10
        caches:
          - pip
        script:
          - pip install pipenv
          - pipenv install --deploy --system --dev
          - python setup.py bdist_wheel --universal
    - step:
        name: Deploy to production
        deployment: production
        max-time: 10
        caches:
          - pip
        trigger: manual
        script:
          - pip install pipenv
          - pipenv install --deploy --system --dev
          - python setup.py bdist_wheel --universal
          - twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD --skip-existing dist/*
