image: python:3.7

pipelines:
  default:
    - step:
        name: Build and test
        max-time: 10
        caches:
          - pip
          - poetry
        script:
          - pip install poetry
          - poetry install
          - poetry run pylint --rcfile .pylintrc pyvisainstrument
          - NI_VISA_PATH='@py' poetry run pytest tests/
    - step:
        name: Deploy to test
        deployment: test
        max-time: 10
        caches:
          - pip
          - poetry
        script:
          - pip install poetry
          - poetry install
          - poetry run pylint --rcfile .pylintrc pyvisainstrument
          - NI_VISA_PATH='@py' poetry run pytest tests/
    - step:
        name: Deploy to staging
        deployment: staging
        max-time: 10
        caches:
          - pip
          - poetry
        script:
          - pip install poetry
          - poetry build
          - poetry publish -u $PYPI_USERNAME -p $PYPI_PASSWORD --dry-run
    - step:
        name: Deploy to production
        deployment: production
        max-time: 10
        caches:
          - pip
        trigger: manual
        script:
          - pip install poetry
          - poetry build
          - poetry publish -u $PYPI_USERNAME -p $PYPI_PASSWORD

definitions:
  caches:
    poetry: .venv